name: social
description: Social-App with firebase


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  hexcolor: ^2.0.7
  shared_preferences: ^2.0.15
  get_storage: ^2.0.3
  flutter_native_splash: 2.2.6
  get: ^4.6.5
  simple_animations: ^4.2.0
  introduction_screen: ^3.0.2
  smooth_page_indicator: ^1.0.0+2
  font_awesome_flutter: ^10.1.0
  loading_animation_widget: ^1.2.0+2
  country_code_picker: ^2.0.2
  image_picker: ^0.8.5+3
  intl: ^0.17.0

  #firebase
  firebase_core: 1.20.0
  firebase_auth: 3.5.1
  cloud_firestore: 3.4.1
  firebase_storage: 10.3.3
  firebase_messaging: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Images/logo.png"
  web: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/Images/logo.png
  adroid: true
  ios: true
  web: true

flutter:

  uses-material-design: true

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/Fonts/RobotoCondensed.ttf
  assets:
    - assets/Fonts/RobotoCondensed.ttf
    - assets/Images/loginpage.png
    - assets/Images/logo.png
    - assets/Images/regpage.png
    - assets/Images/w.png
    - assets/Images/w2.png
    - assets/Images/w3.png
