/// Generated by AssetsRefGenerator on 2022/07/23
class Res {
  static const String loginpage = "assets/Images/loginpage.png";
  static const String logo = "assets/Images/logo.png";
  static const String regpage = "assets/Images/regpage.png";
  static const String RobotoCondensed = "assets/Fonts/RobotoCondensed.ttf";
  static const String w = "assets/Images/w.png";
  static const String w2 = "assets/Images/w2.png";
  static const String w3 = "assets/Images/w3.png";
}
